# Huge, MEE SUSTech
# Email: zhuhu00@foxmail.com

version: '2.3'
services:
  orbslam:
    image: zhuhu/orbslam:cuda102
    build: .

    command: lxterminal
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../ORB-SLAM2-Dense:/root/orbslam2
      - ${DATASET_DIR}:/root/Dataset

    entrypoint: /ros_entrypoint.sh
    network_mode: host

volumes:
  orbslam: